"""empty message

Revision ID: 581ea5257e16
Revises: 087013d6be3e
Create Date: 2022-07-20 12:58:53.311391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581ea5257e16'
down_revision = '087013d6be3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    # ### end Alembic commands ###
